stages:
  scrape-properties:
    cmd: scrape-properties data/2021-01-16T20:40:36+09:00/東京都.zip --output-filename
      data/2021-01-16T20:40:36+09:00/東京都.pickle --output-format pickle --jobs 3
    deps:
    - ../libs/otokuna
    - data/2021-01-16T20:40:36+09:00/東京都.zip
    outs:
    - data/2021-01-16T20:40:36+09:00/東京都.pickle
  train:
    cmd: ./train.py
    deps:
    - ../libs/otokuna
    - data/2021-01-16T20:40:36+09:00/東京都.pickle
    - train.py
    outs:
    - models/regressor.cbm
    - models/regressor.onnx
    metrics:
    - metrics.json:
        cache: false
  check-onnx:
    cmd: ./check_onnx.py
    deps:
    - check_onnx.py
    - data/2021-01-16T20:40:36+09:00/東京都.pickle
    - models/regressor.cbm
    - models/regressor.onnx
    metrics:
    - check_onnx.json:
        cache: false
