# Parameters for the Flask app
secret_key: "some_key"
users:
  - user_id: "some_id0"
    password_hash: "some_hash0"
  - user_id: "some_id1"
    password_hash: "some_hash1"
state_data_path: "/tmp/dtale_data"
bucket_name: "mybucket"
scraped_data_key_prefix: "dumped_data/daily"
scraped_data_key_template: "{}/東京都.pickle"  # relative to scraped_data_key_prefix
predictions_key_prefix: "predictions/daily"
prediction_key_template: "{}/prediction.pickle"  # relative to predictions_key_prefix
prediction_key_pattern: "(.*)/prediction.pickle"  # relative to predictions_key_prefix
